/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snow;

import java.util.ArrayList;
import java.util.List;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

    GraphicsContext g;
    private final double SCREENWIDTH = 600;
    private final double SCREENHEIGHT = 600;
    private final int NUMOFFLAKES = 2000;

    private List<Snowflake> flakes = new ArrayList<>();
    
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        var scene = new Scene(setupScene());
        stage.setScene(scene);
        stage.show();
        
    }

    private Parent setupScene() {
        for (int i = 0; i < NUMOFFLAKES; i++) {
            double x = Math.random() * SCREENWIDTH;
            double y = Math.random() * SCREENHEIGHT;
            flakes.add(new Snowflake(x, y));
        }

        Pane pane = new Pane();
        pane.setPrefSize(SCREENWIDTH, SCREENHEIGHT);
        pane.setStyle("-fx-background-color: black");
        var canvas = new Canvas(SCREENWIDTH, SCREENHEIGHT);
        g = canvas.getGraphicsContext2D();


        AnimationTimer timer = new AnimationTimer() {
            public void handle(long now) {
                onUpdate();
            }
        };
        timer.start();

        pane.getChildren().add(canvas);
        return pane;
    }

    protected void onUpdate() {
        g.clearRect(0, 0, SCREENWIDTH, SCREENHEIGHT);
        flakes.forEach(f -> {
            f.update();
            g.setFill(f.color);
            g.fillOval(f.x, f.y, f.size, f.size);
            if (f.y >= SCREENHEIGHT) {
                f.x = Math.random()*SCREENWIDTH;
                f.y = 0.0;
                f.counter = Math.random()*0.2;
            }                
        });
    }
}
