/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snow;

import org.junit.jupiter.api.Test;

import snow.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
